import { api } from "@/lib/api";
import type {
  Student,
  StudentCustomFieldDefinition,
} from "@/types";
import type { PaymentMethod } from "@/types/payment";

export type StudentFinanceInput = {
  totalRequired: number;
  initialPayment?: number;
  paymentMethod?: PaymentMethod;
  period?: string;
  dueDate?: string;
};

export type CreateStudentInput = Omit<
  Student,
  "id" | "createdAt" | "updatedAt" | "studentId" | "financial"
> & {
  // Auto-generated by backend (STU-YYYY-XXXX) — never sent manually
  studentId?: never;
  /** بيانات مالية تُنشأ ذرياً مع الطالب (فاتورة + دفعة أولى) */
  finance?: StudentFinanceInput;
};
export type UpdateStudentInput = Partial<Omit<Student, "id" | "createdAt" | "studentId">>;

export const studentService = {
  list: async (params?: {
    search?: string;
    groupId?: string;
    teacherId?: string;
    status?: string;
    page?: number;
    limit?: number;
  }): Promise<Student[]> => {
    const res = await api.get<Student[]>("/students", params as Record<string, string>);
    return res.data;
  },

  getById: async (id: string): Promise<Student | null> => {
    try {
      const res = await api.get<Student>(`/students/${id}`);
      return res.data;
    } catch {
      return null;
    }
  },

  getByBarcode: async (code: string): Promise<Student | null> => {
    try {
      const res = await api.get<Student>(`/students/barcode/${encodeURIComponent(code)}`);
      return res.data;
    } catch {
      return null;
    }
  },

  create: async (student: CreateStudentInput): Promise<Student> => {
    const res = await api.post<Student>("/students", student);
    return res.data;
  },

  update: async (
    id: string,
    updates: UpdateStudentInput,
  ): Promise<Student | null> => {
    try {
      const res = await api.put<Student>(`/students/${id}`, updates);
      return res.data;
    } catch {
      return null;
    }
  },

  delete: async (id: string): Promise<boolean> => {
    await api.delete(`/students/${id}`);
    return true;
  },

  // ─── Custom Fields ──────────────────────────────────────────────────────────

  customFields: async (): Promise<StudentCustomFieldDefinition[]> => {
    const res = await api.get<StudentCustomFieldDefinition[]>(
      "/students/custom-fields",
    );
    return res.data;
  },

  createCustomField: async (
    definition: StudentCustomFieldDefinition,
  ): Promise<StudentCustomFieldDefinition> => {
    const res = await api.post<StudentCustomFieldDefinition>(
      "/students/custom-fields",
      definition,
    );
    return res.data;
  },

  deleteCustomField: async (fieldId: string): Promise<boolean> => {
    try {
      await api.delete(`/students/custom-fields/${fieldId}`);
      return true;
    } catch {
      return false;
    }
  },
};
