
"use client";

import {
  useEffect,
  useState,
  type FormEvent,
  type ReactNode,
} from "react";

import {
  FiChevronDown,
  FiPlus,
  FiSave,
  FiTrash2,
  FiUserPlus,
  FiX,
} from "react-icons/fi";

import type {
  Student,
  StudentCustomFieldDefinition,
  StudentCustomFieldValue,
  StudentStatus,
} from "@/types";
import {
  PAYMENT_METHOD_LABELS,
  type PaymentMethod,
} from "@/types/payment";

import { groupService, studentService } from "@/services";

export type StudentFormData = {
  // NOTE: studentId is auto-generated by the backend (STU-YYYY-XXXX).
  // Kept as optional for edit-mode display only — never entered manually on add.
  studentId?: string;
  name: string;
  phone: string;
  guardianName: string;
  guardianPhone: string;
  grade: string;
  groupId: string;
  address: string;
  status: StudentStatus;
  notes: string;
  customFields: StudentCustomFieldValue[];
  totalRequired?: number;
  initialPayment?: number;
  paymentMethod?: PaymentMethod;
};

type StudentModalProps = {
  open: boolean;
  onClose: () => void;
  onSubmit: (
    student: StudentFormData,
  ) => void | Promise<void>;
  initialData?: Student | null;
  mode?: "add" | "edit";
  showFinancialFields?: boolean;
};

const emptyForm: StudentFormData = {
  studentId: "",
  name: "",
  phone: "",
  guardianName: "",
  guardianPhone: "",
  grade: "",
  groupId: "",
  address: "",
  status: "active",
  notes: "",
  customFields: [],
  totalRequired: 0,
  initialPayment: 0,
  paymentMethod: "cash",
};

type GroupOption = {
  id: string;
  name: string;
};

const grades = [
  "أولى إعدادي",
  "ثانية إعدادي",
  "ثالثة إعدادي",
  "أولى ثانوي",
  "ثانية ثانوي",
  "ثالثة ثانوي",
];

const PHONE_REGEX = /^[0-9+\s-]{8,15}$/;

function createInitialForm(
  initialData?: Student | null,
): StudentFormData {
  if (!initialData) {
    return {
      ...emptyForm,
      customFields: [],
      totalRequired: 0,
      initialPayment: 0,
      paymentMethod: "cash",
    };
  }

  return {
    studentId: initialData.studentId ?? "",
    name: initialData.name,
    phone: initialData.phone ?? "",
    guardianName: initialData.guardianName,
    guardianPhone: initialData.guardianPhone,
    grade: initialData.grade,
    groupId: initialData.groupId ?? "",
    address: initialData.address ?? "",
    status: initialData.status,
    notes: initialData.notes ?? "",
    customFields: initialData.customFields ?? [],
    totalRequired:
      initialData.financial?.totalRequired ?? 0,
    initialPayment:
      initialData.financial?.paid ?? 0,
    paymentMethod: "cash",
  };
}

export default function StudentModal(
  props: StudentModalProps,
) {
  if (!props.open) {
    return null;
  }

  const formKey = props.initialData
    ? `edit-${props.initialData.id}`
    : "add";

  return (
    <StudentModalContent
      key={formKey}
      {...props}
    />
  );
}

function StudentModalContent({
  open,
  onClose,
  onSubmit,
  initialData = null,
  mode = "add",
  showFinancialFields = false,
}: StudentModalProps) {
  const [form, setForm] =
    useState<StudentFormData>(() =>
      createInitialForm(initialData),
    );

  const [errors, setErrors] =
    useState<
      Partial<
        Record<keyof StudentFormData, string>
      >
    >({});

  const [
    customFieldDefinitions,
    setCustomFieldDefinitions,
  ] = useState<StudentCustomFieldDefinition[]>(
    [],
  );

  const [
    customFieldsLoading,
    setCustomFieldsLoading,
  ] = useState(false);

  const [
    customFieldSaving,
    setCustomFieldSaving,
  ] = useState(false);

  const [
    showAddCustomField,
    setShowAddCustomField,
  ] = useState(false);

  const [
    submitting,
    setSubmitting,
  ] = useState(false);

  const [
    groups,
    setGroups,
  ] = useState<GroupOption[]>([]);

  const [
    groupsLoading,
    setGroupsLoading,
  ] = useState(false);

  const [
    submitError,
    setSubmitError,
  ] = useState<string | null>(null);

  const [
    newCustomField,
    setNewCustomField,
  ] = useState<{
    label: string;
    type: StudentCustomFieldDefinition["type"];
    required: boolean;
    options: string;
  }>({
    label: "",
    type: "text",
    required: false,
    options: "",
  });

  useEffect(() => {
    if (!open) {
      return;
    }

    let mounted = true;

    const loadCustomFields = async () => {
      try {
        setCustomFieldsLoading(true);

        const definitions =
          await studentService.customFields();

        if (!mounted) {
          return;
        }

        const sortedDefinitions = [
          ...definitions,
        ].sort(
          (a, b) => a.order - b.order,
        );

        setCustomFieldDefinitions(
          sortedDefinitions,
        );
      } catch {
        if (mounted) {
          setCustomFieldDefinitions([]);
        }
      } finally {
        if (mounted) {
          setCustomFieldsLoading(false);
        }
      }
    };

    void loadCustomFields();

    return () => {
      mounted = false;
    };
  }, [open]);

  useEffect(() => {
    if (!open) {
      return;
    }

    let mounted = true;

    const loadGroups = async () => {
      try {
        setGroupsLoading(true);

        const list = await groupService.list();

        if (!mounted) {
          return;
        }

        const activeGroups: GroupOption[] = list
          .filter((group) => group.status !== "inactive")
          .map((group) => ({
            id: group.id,
            name: group.name,
          }));

        setGroups(activeGroups);
      } catch {
        if (mounted) {
          setGroups([]);
        }
      } finally {
        if (mounted) {
          setGroupsLoading(false);
        }
      }
    };

    void loadGroups();

    return () => {
      mounted = false;
    };
  }, [open]);

  // Close modal on Escape key
  useEffect(() => {
    if (!open) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        onClose();
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [open, onClose]);

  // Protect against unsaved data loss
  useEffect(() => {
    if (!open) return;
    const handleBeforeUnload = (e: BeforeUnloadEvent) => {
      if (form.name || form.guardianName || form.phone) {
        e.preventDefault();
        e.returnValue = "";
      }
    };
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => window.removeEventListener("beforeunload", handleBeforeUnload);
  }, [open, form.name, form.guardianName, form.phone]);

  const isEdit = mode === "edit";

  const updateField = <
    K extends keyof StudentFormData
  >(
    field: K,
    value: StudentFormData[K],
  ) => {
    setForm((current) => ({
      ...current,
      [field]: value,
    }));

    setErrors((current) => ({
      ...current,
      [field]: undefined,
    }));

    setSubmitError(null);
  };

  const getCustomFieldValue = (
    fieldId: string,
  ) =>
    form.customFields.find(
      (field) =>
        field.fieldId === fieldId,
    )?.value ?? null;

  const updateCustomFieldValue = (
    fieldId: string,
    value:
      | string
      | number
      | boolean
      | null,
  ) => {
    setForm((current) => {
      const existingIndex =
        current.customFields.findIndex(
          (field) =>
            field.fieldId === fieldId,
        );

      if (existingIndex === -1) {
        return {
          ...current,
          customFields: [
            ...current.customFields,
            {
              fieldId,
              value,
            },
          ],
        };
      }

      const nextCustomFields = [
        ...current.customFields,
      ];

      nextCustomFields[existingIndex] = {
        ...nextCustomFields[existingIndex],
        value,
      };

      return {
        ...current,
        customFields: nextCustomFields,
      };
    });

    setErrors((current) => ({
      ...current,
      customFields: undefined,
    }));

    setSubmitError(null);
  };

  const addCustomFieldDefinition =
    async () => {
      const label =
        newCustomField.label.trim();

      if (!label) {
        return;
      }

      if (
        newCustomField.type === "select" &&
        !newCustomField.options.trim()
      ) {
        return;
      }

      setCustomFieldSaving(true);

      try {
        const id = `custom-${Date.now()}`;

        const options =
          newCustomField.type === "select"
            ? newCustomField.options
                .split(",")
                .map((option) =>
                  option.trim(),
                )
                .filter(Boolean)
            : undefined;

        const definition: StudentCustomFieldDefinition =
          {
            id,
            label,
            type: newCustomField.type,
            required:
              newCustomField.required,
            options,
            active: true,
            order:
              customFieldDefinitions.length +
              1,
          };

        const createdDefinition =
          await studentService.createCustomField(
            definition,
          );

        setCustomFieldDefinitions(
          (current) =>
            [
              ...current,
              createdDefinition,
            ].sort(
              (a, b) =>
                a.order - b.order,
            ),
        );

        setForm((current) => ({
          ...current,
          customFields: [
            ...current.customFields,
            {
              fieldId:
                createdDefinition.id,
              value:
                createdDefinition.type ===
                "boolean"
                  ? false
                  : null,
            },
          ],
        }));

        setNewCustomField({
          label: "",
          type: "text",
          required: false,
          options: "",
        });

        setShowAddCustomField(false);
      } catch (error) {
        const message =
          error instanceof Error
            ? error.message
            : "تعذر إضافة الحقل";

        window.alert(message);
      } finally {
        setCustomFieldSaving(false);
      }
    };

  const removeCustomFieldDefinition =
    async (
      fieldId: string,
    ) => {
      if (!window.confirm("هل أنت متأكد من رغبتك في حذف هذا الحقل المخصص نهائياً؟")) {
        return;
      }
      try {
        const removed =
          await studentService.deleteCustomField(
            fieldId,
          );

        if (!removed) {
          return;
        }

        setCustomFieldDefinitions(
          (current) =>
            current.filter(
              (field) =>
                field.id !== fieldId,
            ),
        );

        setForm((current) => ({
          ...current,
          customFields:
            current.customFields.filter(
              (field) =>
                field.fieldId !==
                fieldId,
            ),
        }));
      } catch (error) {
        const message =
          error instanceof Error
            ? error.message
            : "تعذر حذف الحقل";

        window.alert(message);
      }
    };

  const validate = () => {
    const nextErrors: Partial<
      Record<
        keyof StudentFormData,
        string
      >
    > = {};

    // No manual ID on add — the backend auto-generates STU-YYYY-XXXX on save.
    // In edit mode the code is read-only (immutable), so no validation needed.
    void isEdit;

    if (!form.name.trim()) {
      nextErrors.name =
        "اسم الطالب مطلوب";
    }

    if (!form.phone.trim()) {
      nextErrors.phone =
        "رقم الهاتف مطلوب";
    } else if (
      !PHONE_REGEX.test(
        form.phone.trim(),
      )
    ) {
      nextErrors.phone =
        "رقم الهاتف غير صحيح";
    }

    if (!form.guardianName.trim()) {
      nextErrors.guardianName =
        "اسم ولي الأمر مطلوب";
    }

    if (!form.guardianPhone.trim()) {
      nextErrors.guardianPhone =
        "رقم ولي الأمر مطلوب";
    } else if (
      !PHONE_REGEX.test(
        form.guardianPhone.trim(),
      )
    ) {
      nextErrors.guardianPhone =
        "رقم ولي الأمر غير صحيح";
    }

    if (!form.grade) {
      nextErrors.grade =
        "اختر المرحلة الدراسية";
    }

    if (!form.groupId) {
      nextErrors.groupId =
        "اختر المجموعة";
    }

    if (
      showFinancialFields &&
      !isEdit
    ) {
      const totalRequired =
        Number(
          form.totalRequired ?? 0,
        );

      const initialPayment =
        Number(
          form.initialPayment ?? 0,
        );

      if (
        !Number.isFinite(
          totalRequired,
        ) ||
        totalRequired < 0
      ) {
        nextErrors.totalRequired =
          "أدخل قيمة صحيحة للمبلغ المطلوب";
      }

      if (
        !Number.isFinite(
          initialPayment,
        ) ||
        initialPayment < 0
      ) {
        nextErrors.initialPayment =
          "أدخل قيمة صحيحة للمبلغ المدفوع";
      } else if (
        initialPayment >
        totalRequired
      ) {
        nextErrors.initialPayment =
          "المبلغ المدفوع لا يمكن أن يتجاوز إجمالي المطلوب";
      } else if (
        initialPayment > 0 &&
        !form.paymentMethod
      ) {
        nextErrors.paymentMethod =
          "اختر طريقة الدفع للمبلغ المدفوع";
      }
    }

    customFieldDefinitions
      .filter(
        (field) =>
          field.active &&
          field.required,
      )
      .forEach((field) => {
        const value =
          getCustomFieldValue(
            field.id,
          );

        const isEmpty =
          value === null ||
          value === undefined ||
          value === "" ||
          (typeof value === "string" &&
            !value.trim());

        if (isEmpty) {
          nextErrors.customFields =
            "يرجى إدخال جميع الحقول المطلوبة";
        }
      });

    setErrors(nextErrors);

    return (
      Object.keys(nextErrors)
        .length === 0
    );
  };

  const handleSubmit = async (
    event: FormEvent<HTMLFormElement>,
  ) => {
    event.preventDefault();

    setSubmitError(null);

    if (!validate()) {
      return;
    }

    setSubmitting(true);

    try {
      const { studentId: _ignored, ...rest } = form;
      void _ignored;
      await onSubmit({
        ...rest,
        // Edit mode keeps the existing code for display only; the backend
        // ignores it (student_code is immutable). Add mode sends nothing.
        ...(isEdit && form.studentId
          ? { studentId: form.studentId.trim() }
          : {}),
        name: form.name.trim(),
        phone: form.phone.trim(),
        guardianName:
          form.guardianName.trim(),
        guardianPhone:
          form.guardianPhone.trim(),
        address:
          form.address.trim(),
        notes:
          form.notes.trim(),
        totalRequired:
          showFinancialFields &&
          !isEdit
            ? Math.max(
                Number(
                  form.totalRequired ??
                    0,
                ),
                0,
              )
            : undefined,
        initialPayment:
          showFinancialFields &&
          !isEdit
            ? Math.max(
                Number(
                  form.initialPayment ??
                    0,
                ),
                0,
              )
            : undefined,
        paymentMethod:
          showFinancialFields &&
          !isEdit &&
          Number(form.initialPayment ?? 0) > 0
            ? (form.paymentMethod ?? "cash")
            : undefined,
        customFields:
          form.customFields,
      });
    } catch (error) {
      const message =
        error instanceof Error
          ? error.message
          : "تعذر حفظ بيانات الطالب";

      setSubmitError(message);

      throw error;
    } finally {
      setSubmitting(false);
    }
  };

  const totalRequired =
    Math.max(
      Number(
        form.totalRequired ?? 0,
      ),
      0,
    );

  const initialPayment =
    Math.max(
      Number(
        form.initialPayment ?? 0,
      ),
      0,
    );

  const remainingAmount =
    Math.max(
      totalRequired -
        initialPayment,
      0,
    );

  return (
    <div
      className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/40 p-4 backdrop-blur-[2px]"
      onMouseDown={(event) => {
        if (
          event.target ===
          event.currentTarget
        ) {
          onClose();
        }
      }}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="student-modal-title"
        className="flex max-h-[92vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"
      >
        <div className="flex shrink-0 items-center justify-between border-b border-slate-100 px-5 py-4 sm:px-6">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EDF2FF] text-[#1748EF]">
              {isEdit ? (
                <FiSave size={18} />
              ) : (
                <FiUserPlus size={18} />
              )}
            </div>

            <div>
              <h2
                id="student-modal-title"
                className="text-base font-bold text-slate-900"
              >
                {isEdit
                  ? "تعديل بيانات الطالب"
                  : "إضافة طالب جديد"}
              </h2>

              <p className="mt-0.5 text-xs text-slate-400">
                {isEdit
                  ? "قم بتحديث بيانات الطالب ثم احفظ التغييرات."
                  : "أدخل البيانات الأساسية للطالب وولي الأمر."}
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            aria-label="إغلاق"
            disabled={submitting}
            className="flex h-9 w-9 items-center justify-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-700 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <FiX size={19} />
          </button>
        </div>

        {submitError && (
          <div className="shrink-0 border-b border-red-100 bg-red-50 px-5 py-3 sm:px-6">
            <div
              role="alert"
              className="flex items-start gap-2"
            >
              <div className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-red-100 text-[11px] font-bold text-red-600">
                !
              </div>

              <div>
                <p className="text-xs font-bold text-red-700">
                  تعذر حفظ الطالب
                </p>

                <p className="mt-0.5 text-xs text-red-600">
                  {submitError}
                </p>
              </div>
            </div>
          </div>
        )}

        <form
          onSubmit={handleSubmit}
          className="flex min-h-0 flex-1 flex-col"
        >
          <div className="flex-1 overflow-y-auto px-5 py-5 sm:px-6">
            <section>
              <div className="mb-4">
                <h3 className="text-sm font-bold text-slate-800">
                  بيانات الطالب
                </h3>

                <p className="mt-1 text-xs text-slate-400">
                  المعلومات الأساسية للطالب
                </p>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                {isEdit ? (
                  <Field label="رقم الطالب (تلقائي)">
                    <input
                      dir="ltr"
                      value={form.studentId ?? ""}
                      disabled
                      readOnly
                      aria-label="رقم الطالب (يتم توليده تلقائياً ولا يمكن تعديله)"
                      className={`${inputClass(false)} cursor-not-allowed bg-slate-100 text-left text-slate-500`}
                    />
                  </Field>
                ) : (
                  <div className="sm:col-span-2">
                    <div className="flex items-start gap-2 rounded-xl border border-[#DCE5FF] bg-[#EDF2FF]/60 px-3 py-2.5">
                      <div className="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#DCE5FF] text-[11px] font-bold text-[#1748EF]">
                        ✓
                      </div>
                      <p className="text-xs leading-5 text-[#10275B]">
                        سيتم توليد كود الطالب تلقائياً عند الحفظ (مثال: STU-2026-0001) — لا حاجة لإدخاله يدوياً.
                      </p>
                    </div>
                  </div>
                )}

                <Field
                  label="اسم الطالب"
                  required
                  error={errors.name}
                >
                  <input
                    value={form.name}
                    onChange={(event) =>
                      updateField(
                        "name",
                        event.target.value,
                      )
                    }
                    placeholder="مثال: أحمد محمد علي"
                    className={inputClass(
                      Boolean(
                        errors.name,
                      ),
                    )}
                  />
                </Field>

                <Field
                  label="رقم الهاتف"
                  required
                  error={errors.phone}
                >
                  <input
                    dir="ltr"
                    type="tel"
                    inputMode="tel"
                    value={form.phone}
                    onChange={(event) =>
                      updateField(
                        "phone",
                        event.target.value,
                      )
                    }
                    placeholder="01012345678"
                    className={`${inputClass(
                      Boolean(
                        errors.phone,
                      ),
                    )} text-left`}
                  />
                </Field>

                <Field
                  label="المرحلة الدراسية"
                  required
                  error={errors.grade}
                >
                  <SelectField
                    value={form.grade}
                    onChange={(value) =>
                      updateField(
                        "grade",
                        value,
                      )
                    }
                    placeholder="اختر المرحلة"
                    error={Boolean(
                      errors.grade,
                    )}
                    options={grades}
                  />
                </Field>

                <Field
                  label="المجموعة"
                  required
                  error={errors.groupId}
                >
                  <SelectField
                    value={
                      form.groupId
                    }
                    onChange={(value) =>
                      updateField(
                        "groupId",
                        value,
                      )
                    }
                    placeholder={
                      groupsLoading
                        ? "جاري تحميل المجموعات..."
                        : groups.length === 0
                          ? "لا توجد مجموعات متاحة"
                          : "اختر المجموعة"
                    }
                    error={Boolean(
                      errors.groupId,
                    )}
                    options={groups.map(
                      (group) =>
                        `${group.id}|||${group.name}`,
                    )}
                    renderOption={(option) => {
                      const [, name] =
                        option.split(
                          "|||",
                        );

                      return name;
                    }}
                  />
                </Field>

                <Field label="الحالة">
                  <SelectField
                    value={form.status}
                    onChange={(value) =>
                      updateField(
                        "status",
                        value as StudentStatus,
                      )
                    }
                    options={[
                      "active",
                      "inactive",
                      "suspended",
                    ]}
                    renderOption={(option) => {
                      if (
                        option ===
                        "active"
                      ) {
                        return "نشط";
                      }

                      if (
                        option ===
                        "inactive"
                      ) {
                        return "غير نشط";
                      }

                      return "متوقف";
                    }}
                  />
                </Field>

                <Field label="العنوان">
                  <input
                    value={form.address}
                    onChange={(event) =>
                      updateField(
                        "address",
                        event.target.value,
                      )
                    }
                    placeholder="مثال: طنطا"
                    className={inputClass(
                      false,
                    )}
                  />
                </Field>
              </div>
            </section>

            {showFinancialFields &&
              !isEdit && (
                <section className="mt-7 border-t border-slate-100 pt-6">
                  <div className="mb-4">
                    <h3 className="text-sm font-bold text-slate-800">
                      الاشتراك والمصروفات
                    </h3>

                    <p className="mt-1 text-xs text-slate-400">
                      حدد إجمالي المطلوب والمبلغ المدفوع عند التسجيل.
                    </p>
                  </div>

                  <div className="grid gap-4 sm:grid-cols-2">
                    <Field
                      label="إجمالي المطلوب"
                      required
                      error={
                        errors.totalRequired
                      }
                    >
                      <input
                        dir="ltr"
                        type="number"
                        min="0"
                        step="0.01"
                        inputMode="decimal"
                        value={
                          form.totalRequired ??
                          0
                        }
                        onChange={(event) =>
                          updateField(
                            "totalRequired",
                            Number(
                              event.target
                                .value,
                            ),
                          )
                        }
                        placeholder="مثال: 1500"
                        className={`${inputClass(
                          Boolean(
                            errors.totalRequired,
                          ),
                        )} text-left`}
                      />
                    </Field>

                    <Field
                      label="المبلغ المدفوع"
                      required
                      error={
                        errors.initialPayment
                      }
                    >
                      <input
                        dir="ltr"
                        type="number"
                        min="0"
                        step="0.01"
                        inputMode="decimal"
                        value={
                          form.initialPayment ??
                          0
                        }
                        onChange={(event) =>
                          updateField(
                            "initialPayment",
                            Number(
                              event.target
                                .value,
                            ),
                          )
                        }
                        placeholder="مثال: 500"
                        className={`${inputClass(
                          Boolean(
                            errors.initialPayment,
                          ),
                        )} text-left`}
                      />
                    </Field>
                  </div>

                  <div className="mt-4">
                    <Field
                      label="طريقة الدفع"
                      required={
                        Number(
                          form.initialPayment ??
                            0,
                        ) > 0
                      }
                      error={
                        errors.paymentMethod
                      }
                    >
                      <div className="relative">
                        <select
                          value={
                            form.paymentMethod ??
                            "cash"
                          }
                          onChange={(event) =>
                            updateField(
                              "paymentMethod",
                              event.target
                                .value as PaymentMethod,
                            )
                          }
                          className={`${inputClass(
                            Boolean(
                              errors.paymentMethod,
                            ),
                          )} appearance-none pl-9`}
                        >
                          {(
                            Object.keys(
                              PAYMENT_METHOD_LABELS,
                            ) as PaymentMethod[]
                          ).map(
                            (method) => (
                              <option
                                key={method}
                                value={method}
                              >
                                {
                                  PAYMENT_METHOD_LABELS[
                                    method
                                  ]
                                }
                              </option>
                            ),
                          )}
                        </select>

                        <FiChevronDown
                          size={15}
                          className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
                        />
                      </div>
                    </Field>
                  </div>

                  <div className="mt-4 grid grid-cols-3 gap-2">                    <div className="rounded-xl border border-slate-200 bg-slate-50 p-3 text-center">
                      <p className="text-[10px] text-slate-400">
                        المطلوب
                      </p>

                      <p className="mt-1 text-sm font-bold text-slate-800">
                        {totalRequired}
                      </p>
                    </div>

                    <div className="rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-center">
                      <p className="text-[10px] text-emerald-600">
                        المدفوع
                      </p>

                      <p className="mt-1 text-sm font-bold text-emerald-700">
                        {initialPayment}
                      </p>
                    </div>

                    <div className="rounded-xl border border-amber-100 bg-amber-50 p-3 text-center">
                      <p className="text-[10px] text-amber-600">
                        المتبقي
                      </p>

                      <p className="mt-1 text-sm font-bold text-amber-700">
                        {remainingAmount}
                      </p>
                    </div>
                  </div>
                </section>
              )}

            <section className="mt-7 border-t border-slate-100 pt-6">
              <div className="mb-4">
                <h3 className="text-sm font-bold text-slate-800">
                  بيانات ولي الأمر
                </h3>

                <p className="mt-1 text-xs text-slate-400">
                  بيانات التواصل مع ولي الأمر
                </p>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <Field
                  label="اسم ولي الأمر"
                  required
                  error={
                    errors.guardianName
                  }
                >
                  <input
                    value={
                      form.guardianName
                    }
                    onChange={(event) =>
                      updateField(
                        "guardianName",
                        event.target.value,
                      )
                    }
                    placeholder="مثال: محمد علي"
                    className={inputClass(
                      Boolean(
                        errors.guardianName,
                      ),
                    )}
                  />
                </Field>

                <Field
                  label="رقم هاتف ولي الأمر"
                  required
                  error={
                    errors.guardianPhone
                  }
                >
                  <input
                    dir="ltr"
                    type="tel"
                    inputMode="tel"
                    value={
                      form.guardianPhone
                    }
                    onChange={(event) =>
                      updateField(
                        "guardianPhone",
                        event.target.value,
                      )
                    }
                    placeholder="01011112222"
                    className={`${inputClass(
                      Boolean(
                        errors.guardianPhone,
                      ),
                    )} text-left`}
                  />
                </Field>
              </div>
            </section>

            <section className="mt-7 border-t border-slate-100 pt-6">
              <div className="mb-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h3 className="text-sm font-bold text-slate-800">
                      بيانات إضافية
                    </h3>

                    <p className="mt-1 text-xs text-slate-400">
                      حقول مخصصة يمكن إضافتها حسب احتياج السنتر.
                    </p>
                  </div>

                  <button
                    type="button"
                    onClick={() =>
                      setShowAddCustomField(
                        (current) =>
                          !current,
                      )
                    }
                    disabled={
                      customFieldSaving
                    }
                    className="inline-flex h-9 shrink-0 items-center gap-1.5 rounded-xl border border-[#CCD8FF] bg-[#EDF2FF] px-3 text-xs font-semibold text-[#1748EF] transition hover:border-[#AABEFF] hover:bg-[#E2E9FF] disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <FiPlus size={14} />
                    إضافة خانة جديدة
                  </button>
                </div>
              </div>

              {showAddCustomField && (
                <div className="mb-5 rounded-xl border border-[#DCE5FF] bg-[#EDF2FF]/40 p-4">
                  <div className="grid gap-4 sm:grid-cols-2">
                    <Field
                      label="اسم الخانة"
                      required
                    >
                      <input
                        value={
                          newCustomField.label
                        }
                        onChange={(event) =>
                          setNewCustomField(
                            (current) => ({
                              ...current,
                              label:
                                event.target
                                  .value,
                            }),
                          )
                        }
                        placeholder="مثال: المدرسة"
                        className={inputClass(
                          false,
                        )}
                      />
                    </Field>

                    <Field label="نوع الخانة">
                      <SelectField
                        value={
                          newCustomField.type
                        }
                        onChange={(value) =>
                          setNewCustomField(
                            (current) => ({
                              ...current,
                              type:
                                value as StudentCustomFieldDefinition["type"],
                            }),
                          )
                        }
                        options={[
                          "text",
                          "number",
                          "date",
                          "select",
                          "textarea",
                          "boolean",
                        ]}
                        renderOption={(option) => {
                          const labels: Record<
                            string,
                            string
                          > = {
                            text: "نص",
                            number: "رقم",
                            date: "تاريخ",
                            select: "اختيار",
                            textarea:
                              "نص طويل",
                            boolean:
                              "نعم / لا",
                          };

                          return (
                            labels[
                              option
                            ] ?? option
                          );
                        }}
                      />
                    </Field>
                  </div>

                  <div className="mt-4 flex items-center gap-2">
                    <input
                      id="custom-field-required"
                      type="checkbox"
                      checked={
                        newCustomField.required
                      }
                      onChange={(event) =>
                        setNewCustomField(
                          (current) => ({
                            ...current,
                            required:
                              event.target
                                .checked,
                          }),
                        )
                      }
                      className="h-4 w-4 rounded border-slate-300 text-[#1748EF] focus:ring-[#1748EF]"
                    />

                    <label
                      htmlFor="custom-field-required"
                      className="text-xs font-medium text-slate-600"
                    >
                      هذا الحقل مطلوب
                    </label>
                  </div>

                  {newCustomField.type ===
                    "select" && (
                    <div className="mt-4">
                      <Field label="الاختيارات">
                        <input
                          value={
                            newCustomField.options
                          }
                          onChange={(event) =>
                            setNewCustomField(
                              (current) => ({
                                ...current,
                                options:
                                  event.target
                                    .value,
                              }),
                            )
                          }
                          placeholder="مثال: ممتاز, جيد جدًا, جيد"
                          className={inputClass(
                            false,
                          )}
                        />

                        <p className="mt-1.5 text-[11px] text-slate-400">
                          افصل بين كل اختيار والآخر بفاصلة.
                        </p>
                      </Field>
                    </div>
                  )}

                  <div className="mt-4 flex items-center justify-end gap-2">
                    <button
                      type="button"
                      onClick={() =>
                        setShowAddCustomField(
                          false,
                        )
                      }
                      disabled={
                        customFieldSaving
                      }
                      className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-medium text-slate-600 transition hover:bg-slate-50 disabled:opacity-50"
                    >
                      إلغاء
                    </button>

                    <button
                      type="button"
                      onClick={
                        addCustomFieldDefinition
                      }
                      disabled={
                        customFieldSaving ||
                        !newCustomField.label.trim() ||
                        (newCustomField.type ===
                          "select" &&
                          !newCustomField.options.trim())
                      }
                      className="inline-flex h-9 items-center gap-1.5 rounded-xl bg-[#1748EF] px-3 text-xs font-semibold text-white transition hover:bg-[#123BD0] disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      <FiPlus size={13} />

                      {customFieldSaving
                        ? "جاري الإضافة..."
                        : "إضافة الخانة"}
                    </button>
                  </div>
                </div>
              )}

              {errors.customFields && (
                <p className="mb-4 rounded-lg border border-red-100 bg-red-50 px-3 py-2 text-xs font-medium text-red-600">
                  {errors.customFields}
                </p>
              )}

              {customFieldsLoading ? (
                <div className="rounded-xl border border-slate-100 bg-slate-50 px-4 py-5 text-center text-xs text-slate-400">
                  جاري تحميل الحقول الإضافية...
                </div>
              ) : customFieldDefinitions.filter(
                  (field) =>
                    field.active,
                ).length === 0 ? (
                <div className="rounded-xl border border-dashed border-slate-200 bg-slate-50 px-4 py-5 text-center text-xs text-slate-400">
                  لا توجد حقول إضافية حاليًا.
                  يمكنك إضافة خانة جديدة.
                </div>
              ) : (
                <div className="grid gap-4 sm:grid-cols-2">
                  {customFieldDefinitions
                    .filter(
                      (field) =>
                        field.active,
                    )
                    .sort(
                      (a, b) =>
                        a.order - b.order,
                    )
                    .map((field) => (
                      <CustomFieldInput
                        key={field.id}
                        field={field}
                        value={getCustomFieldValue(
                          field.id,
                        )}
                        onChange={(value) =>
                          updateCustomFieldValue(
                            field.id,
                            value,
                          )
                        }
                        onRemove={() =>
                          void removeCustomFieldDefinition(
                            field.id,
                          )
                        }
                      />
                    ))}
                </div>
              )}
            </section>

            <section className="mt-7 border-t border-slate-100 pt-6">
              <div className="mb-4">
                <h3 className="text-sm font-bold text-slate-800">
                  ملاحظات
                </h3>

                <p className="mt-1 text-xs text-slate-400">
                  معلومات إضافية اختيارية
                </p>
              </div>

              <textarea
                value={form.notes}
                onChange={(event) =>
                  updateField(
                    "notes",
                    event.target.value,
                  )
                }
                placeholder="اكتب أي ملاحظات مهمة عن الطالب..."
                rows={4}
                className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-700 outline-none transition placeholder:text-slate-400 hover:border-slate-300 focus:border-[#1748EF] focus:bg-white focus:ring-4 focus:ring-[#1748EF]/10"
              />
            </section>
          </div>

          <div className="flex shrink-0 items-center justify-end gap-2 border-t border-slate-100 bg-slate-50/70 px-5 py-4 sm:px-6">
            <button
              type="button"
              onClick={onClose}
              disabled={submitting}
              className="h-10 rounded-lg border border-slate-200 bg-white px-4 text-sm font-medium text-slate-600 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              إلغاء
            </button>

            <button
              type="submit"
              disabled={submitting}
              className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-[#1748EF] px-5 text-sm font-semibold text-white transition hover:bg-[#123BD0] active:scale-[0.98] disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isEdit ? (
                <FiSave size={15} />
              ) : (
                <FiUserPlus size={15} />
              )}

              {submitting
                ? "جاري الحفظ..."
                : isEdit
                  ? "حفظ التعديلات"
                  : "إضافة الطالب"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

function CustomFieldInput({
  field,
  value,
  onChange,
  onRemove,
}: {
  field: StudentCustomFieldDefinition;
  value:
    | string
    | number
    | boolean
    | null;
  onChange: (
    value:
      | string
      | number
      | boolean
      | null,
  ) => void;
  onRemove: () => void;
}) {
  const error = false;

  if (field.type === "boolean") {
    return (
      <div className="rounded-xl border border-slate-200 bg-white p-3">
        <div className="flex items-center justify-between gap-3">
          <label className="flex items-center gap-2 text-xs font-semibold text-slate-600">
            <input
              type="checkbox"
              checked={value === true}
              onChange={(event) =>
                onChange(
                  event.target.checked,
                )
              }
              className="h-4 w-4 rounded border-slate-300 text-[#1748EF] focus:ring-[#1748EF]"
            />

            {field.label}

            {field.required && (
              <span className="text-red-500">
                *
              </span>
            )}
          </label>

          <button
            type="button"
            onClick={onRemove}
            aria-label={`حذف ${field.label}`}
            className="flex h-7 w-7 items-center justify-center rounded-md text-slate-300 transition hover:bg-red-50 hover:text-red-500"
          >
            <FiTrash2 size={13} />
          </button>
        </div>
      </div>
    );
  }

  return (
    <Field
      label={field.label}
      required={field.required}
    >
      <div className="relative">
        {field.type === "select" ? (
          <SelectField
            value={
              value === null ||
              value === undefined
                ? ""
                : String(value)
            }
            onChange={(nextValue) =>
              onChange(
                nextValue || null,
              )
            }
            placeholder="اختر..."
            options={field.options ?? []}
            error={error}
          />
        ) : field.type === "textarea" ? (
          <textarea
            value={
              value === null ||
              value === undefined
                ? ""
                : String(value)
            }
            onChange={(event) =>
              onChange(
                event.target.value,
              )
            }
            rows={3}
            className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-700 outline-none transition placeholder:text-slate-400 hover:border-slate-300 focus:border-[#1748EF] focus:bg-white focus:ring-4 focus:ring-[#1748EF]/10"
          />
        ) : (
          <input
            type={
              field.type === "number"
                ? "number"
                : field.type === "date"
                  ? "date"
                  : "text"
            }
            value={
              value === null ||
              value === undefined
                ? ""
                : String(value)
            }
            onChange={(event) => {
              if (
                field.type ===
                "number"
              ) {
                const raw =
                  event.target.value;

                if (raw === "") {
                  onChange(null);
                  return;
                }

                const numericValue =
                  Number(raw);

                if (
                  Number.isFinite(
                    numericValue,
                  )
                ) {
                  onChange(
                    numericValue,
                  );
                }

                return;
              }

              onChange(
                event.target.value,
              );
            }}
            className={inputClass(
              error,
            )}
          />
        )}

        <button
          type="button"
          onClick={onRemove}
          aria-label={`حذف ${field.label}`}
          className="absolute left-2 top-1/2 flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded-md text-slate-300 transition hover:bg-red-50 hover:text-red-500"
        >
          <FiTrash2 size={13} />
        </button>
      </div>
    </Field>
  );
}

function Field({
  label,
  required = false,
  error,
  children,
}: {
  label: string;
  required?: boolean;
  error?: string;
  children: ReactNode;
}) {
  return (
    <div>
      <label className="mb-1.5 block text-xs font-semibold text-slate-600">
        {label}

        {required && (
          <span className="mr-1 text-red-500">
            *
          </span>
        )}
      </label>

      {children}

      {error && (
        <p className="mt-1.5 text-[11px] font-medium text-red-500">
          {error}
        </p>
      )}
    </div>
  );
}

function SelectField({
  value,
  onChange,
  options,
  placeholder,
  error = false,
  renderOption,
}: {
  value: string;
  onChange: (value: string) => void;
  options: string[];
  placeholder?: string;
  error?: boolean;
  renderOption?: (
    option: string,
  ) => string;
}) {
  return (
    <div className="relative">
      <select
        value={value}
        onChange={(event) =>
          onChange(event.target.value)
        }
        className={`${inputClass(
          error,
        )} appearance-none pl-9`}
      >
        {placeholder && (
          <option value="">
            {placeholder}
          </option>
        )}

        {options.map((option) => {
          const optionValue =
            option.includes("|||")
              ? option.split(
                  "|||",
                )[0]
              : option;

          const optionLabel =
            renderOption?.(option) ??
            option;

          return (
            <option
              key={option}
              value={optionValue}
            >
              {optionLabel}
            </option>
          );
        })}
      </select>

      <FiChevronDown
        size={15}
        className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"
      />
    </div>
  );
}

function inputClass(
  error: boolean,
) {
  return `h-10 w-full rounded-lg border bg-slate-50 px-3 text-sm text-slate-700 outline-none transition placeholder:text-slate-400 ${
    error
      ? "border-red-300 focus:border-red-400 focus:ring-4 focus:ring-red-500/10"
      : "border-slate-200 hover:border-slate-300 focus:border-[#1748EF] focus:bg-white focus:ring-4 focus:ring-[#1748EF]/10"
  }`;
}
